spring.application.name=healthcare

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
document.upload.path=uploads
media.upload.path=uploads/media

# ==========================================================
# AI SYMPTOM CHECKER CONFIGURATION
# ==========================================================
ai.api.enabled=false
ai.api.url=https://api.openai.com/v1/chat/completions
ai.api.key=YOUR_API_KEY_HERE
ai.api.model=gpt-4o-mini